[package]
name = "aoc2021-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
aoc-helper = { version = "0.2.1", features = ["config-file"] }
regex = "1"
num = "0.1.42"
